version: '3.0'

services:
    openapi_mock:
        container_name: openapi_mock
        image: muonsoft/openapi-mock
        environment:
            OPENAPI_MOCK_SPECIFICATION_URL: '/app/openapi.json'
        volumes:
            - ./open-api/openapi.json:/app/openapi.json
        ports:
            - "8080:8080"